name: LaPagina
favicon: null
layout_spectrum: 0.62664
typography_spectrum: 0.7148872029501945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e62a36'
    - '#465126'
    - '#eeb8b6'
    - '#0f1305'
  brandStrength: 0.4432693354319781
  lightness: 0.31551480456255376
  saturation: 0.6948045010212809
  rhythmicContrast: 0.2172272561583668
purpose: []
